platform :ios, '9.0'

target 'RnpLog_Example' do
  pod 'RnpLog', :path => '../'
  pod 'AFNetworking'
  pod 'SDWebImage'
end
post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        if target.name == 'RnpLog'
            target.build_configurations.each do |config|
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)','LogForceShow=1']
            end
        end
    end
end
