#use_frameworks!
platform :ios, '9.0'

target 'RnpLog_Example' do
  pod 'RnpLog', :path => '../'
  pod 'AFNetworking'
  pod 'SDWebImage'

  target 'RnpLog_Tests' do
    inherit! :search_paths

    
  end
end
